### ISSUE TITLE
gt911 x cordinate readings issue

### ISSUE THREAD

**Issue by arbymohamed** [DiveInEmbedded/GT911-Touch-driver#3]
hello, thank you for this driver

i started using on a display i am working on and the code works, except the x coordinate seems to be split in 2.
this is what i mean:
Starting from the right side of the display x reads from 0 to about 400, then when i cross the middle of the display it reads from 800 to about 300. these are not the exact value but i think it ilustrates what i am trying to explain.

any help solbing this would be appreciated

thanks again

**Comment by MohsenBiglari** [comment]
Dear @arbymohamed 

I implemented this driver many years ago, and now I can't remember it completely, but I remember having the same problem. Then, I changed the code, and it was fixed. The new source code is attached to this message.

[GT911 (1).zip](https://github.com/user-attachments/files/18929445/GT911.1.zip)

**Comment by arbymohamed** [comment]
thank you for your response, it is still initialized the same way as the old code?

GT911_Config_t sampleConfig = {
		.X_Resolution = 480,
		.Y_Resolution = 854,
		.Number_Of_Touch_Support = 1,
		.ReverseY = true,
		.ReverseX = false,
		.SwithX2Y = false,
		.SoftwareNoiseReduction = true};
TouchCordinate_t cordinate[5];
uint8_t number;

this part precisely

**Comment by arbymohamed** [comment]
i just tried the new code, but the issue still seems to be there

![Image](https://github.com/user-attachments/assets/a59ffb33-8fed-4d0b-84f2-a66c9f15eebf)

you can observe it on the image above

i have a resolution of 480x854, is there a chance i didn't configure the driver properly ?

**Comment by MohsenBiglari** [comment]
@arbymohamed 
Unfortunately, you can find different types of this touch driver with the same label and I think your driver is a fake one. I strongly recommend that buy another one from a different distributor. I hope the new one will work well.

**Comment by arbymohamed** [comment]
i tried another displays that's identical to the faulty one and it work perfectly. I assume maybe something's wrong witht he first display i tried. 

Thank you for the support
